---
- name: Update and upgrade all packages (yum)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat' and must_upgrade_yum
  become: yes

- meta: flush_handlers
# vim:ft=ansible:
